name: stunting_project
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  dartz: ^0.10.1
  dio: ^4.0.6
  expandable: ^5.0.1
  expansion_widget: ^0.0.3
  file_picker: ^5.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^2.0.2
  image_picker: ^1.0.4
  http_parser: ^4.0.2
  intl: ^0.19.0
  percent_indicator: ^4.2.2
  pie_chart: ^5.3.2
  url_launcher: ^6.2.2
  geolocator: ^10.1.0


  cupertino_icons: ^1.0.2



dev_dependencies:
  auto_route_generator: ^5.0.3
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets: ['assets/', ]
  