name: stunting_project
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter_html: ^3.0.0-beta.2
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  dartz: ^0.10.1
  dio: ^5.1.2
  expandable: ^5.0.1
  expansion_widget: ^0.1.0
  file_picker: ^8.0.5
  json_annotation: ^4.9.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.1.1
  flutter_svg: ^2.0.2
  image_picker: ^1.0.4
  http_parser: ^4.0.2
  intl: ^0.19.0
  percent_indicator: ^4.2.2
  pie_chart: ^5.3.2
  url_launcher: ^6.2.2
  geolocator: ^12.0.0


  cupertino_icons: ^1.0.2
  mime: ^1.0.5
  provider: ^6.1.2



dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.5
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets: ['assets/', ]
  